import React from 'react';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-black">
      <div className="max-w-4xl mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold text-white mb-8">Privacy Policy</h1>
        
        <div className="prose prose-lg max-w-none">
          <p className="text-sm text-gray-300 mb-8">
            Last updated: August 1, 2025
          </p>

          <section className="mb-8">
            <p className="text-gray-300 leading-relaxed mb-8">
              Cription Corporation (hereinafter referred to as "we" or "our company") has established this Privacy Policy (hereinafter referred to as "this Policy") as the basic principles to be observed for the appropriate management and operation of user information obtained by our company in the service "Cription" (hereinafter referred to as "this Service") provided by our company, and we will handle user information appropriately.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">1. Consent to Privacy Policy</h2>
            <p className="text-gray-300 leading-relaxed">
              By using this Service or continuing to browse this website, users are deemed to have agreed to this Policy.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">2. User Information Collected and Purpose of Use</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              In this Policy, "User Information" refers to the following information obtained by our company through this Service. When collecting user information, our company will clearly specify the purpose of collection within the scope of legitimate business activities in advance, and will collect and use it to the extent necessary to achieve that purpose through legal and fair methods.
            </p>
            <p className="text-gray-300 leading-relaxed mb-4">
              Our company may change the purpose of use of user information within a range that is reasonably considered to be related to the purpose of use before the change, but when the purpose of use is changed, we will promptly notify or announce it.
            </p>

            <h3 className="text-xl font-medium text-white mb-3">2.1 Information Collected in This Service</h3>
            <p className="text-gray-300 leading-relaxed mb-4">
              Our company may collect the following information from users in this Service. If users do not agree to provide the following information, they cannot use this Service.
            </p>

            <h4 className="text-lg font-medium text-white mb-3">2.1.1 Information Provided by Users When Using This Service</h4>
            <ul className="list-disc pl-6 text-gray-300 mb-4">
              <li>Information necessary for account creation such as User ID (email address), nickname, profile photo, etc.</li>
              <li>Account information of linked services provided through integration functions with other services such as Apple, Microsoft, Google, etc.</li>
              <li>Information about text, photos, audio, video, and other data uploaded by users</li>
              <li>Information about payment methods such as credit card information</li>
              <li>Feedback information from users such as evaluations or complaints</li>
              <li>Information from customer support inquiries</li>
            </ul>

            <h4 className="text-lg font-medium text-white mb-3">2.1.2 Information Collected by Our Company When Users Use This Service</h4>
            <ul className="list-disc pl-6 text-gray-300 mb-4">
              <li>OS of the device used when using this Service, UID (unique identifier) of the application, and version information</li>
              <li>Information about the usage status of this Service (including operation settings, number of file uploads, transcription time, member registration, but not limited to these)</li>
              <li>Information about operations of this Service (including recording, sharing, editing, deletion, but not limited to these)</li>
              <li>Audio data, video data sent to our company when using this Service, text data generated by our company processing user's audio data, translation data, and speech synthesis data, etc.</li>
              <li>Information about access status and usage methods to this Service (including access date and time, Cookie information, but not limited to these)</li>
            </ul>

            <h3 className="text-xl font-medium text-white mb-3">2.2 Purpose and Scope of Use</h3>
            <p className="text-gray-300 leading-relaxed mb-4">
              Our company will use user information (including information that falls under personal information as defined by the Personal Information Protection Law, not limited to user information) for the following purposes and scope of use.
            </p>
            <ul className="list-disc pl-6 text-gray-300 mb-4">
              <li>For registration acceptance, identity verification, and provision, maintenance, protection, and improvement of this Service</li>
              <li>For identity authentication at login or after login when using this Service</li>
              <li>For improvement and enhancement of this Service content and research and development of new services</li>
              <li>For notifying information about this Service content, update information, event and campaign information, and changes to these Terms of Use and this Privacy Policy</li>
              <li>For responding to inquiries and other communications regarding this Service</li>
              <li>For security improvement, prevention of unauthorized use, and other efforts to improve the safety and reliability of this Service</li>
              <li>For creating and using statistical information about this Service within a range that cannot identify individuals</li>
              <li>For planning, formulating, or implementing future services related to this Service</li>
            </ul>
            <p className="text-gray-300 leading-relaxed mb-4">
              This Service uses APIs from third-party partner companies that provide speech recognition engines for speech recognition. These partner companies may use your audio data for speech recognition training depending on the plan you use. The use of this audio data is managed by the company's privacy policy.
            </p>
            <p className="text-gray-300 leading-relaxed mb-4">
              For translation functions in this Service, translation is performed using APIs from third parties that provide translation engines.
            </p>
            <p className="text-gray-300 leading-relaxed">
              For purposes incidental to each of the above purposes of use.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">3. Provision to Third Parties</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              Our company will not provide collected user information to third parties without prior consent from users. However, user information may be provided to third parties (including those outside Japan) in the following cases.
            </p>
            <ul className="list-disc pl-6 text-gray-300">
              <li>When the user has consented</li>
              <li>When the user violates this Policy and we determine that user information must be disclosed to protect the rights and property of our company or other users, this Service, or this website</li>
              <li>When necessary to protect human life, body, or property and it is difficult to obtain the person's consent</li>
              <li>When our company's business succession including user information provision occurs due to merger, company split, business transfer, or other reasons</li>
              <li>When permitted by the Personal Information Protection Law or other laws and regulations</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">4. Disclosure to the Person</h2>
            <p className="text-gray-300 leading-relaxed">
              When requested to disclose personal information based on the provisions of the Personal Information Protection Law, our company will promptly disclose it after confirming that the request is from the person. However, in principle, the disclosure target is limited to information that falls under personal information under the Personal Information Protection Law, and not all user information is subject to disclosure. This does not apply when our company is not obligated to disclose under the Personal Information Protection Law or other laws and regulations.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">5. Correction of User Information</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              When requested by the person to correct, suspend use, or delete user information, our company will respond promptly after confirming that the request is from the person. Please contact us through the contact window listed at the end of this Policy.
            </p>
            <p className="text-gray-300 leading-relaxed">
              We may refuse requests that we determine to be unreasonable, such as when the request content has no reason under laws such as the Personal Information Protection Law, when the request is unreasonably repeated, or when we determine the request to be inappropriate.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">6. Outsourcing of User Information Handling</h2>
            <p className="text-gray-300 leading-relaxed">
              Our company may outsource the handling of collected user information to external parties within the scope necessary to achieve the purpose of use of user information for business operations. In this case, our company will supervise the outsourcing party and ensure appropriate information management.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">7. Protection of Communication Secrets</h2>
            <p className="text-gray-300 leading-relaxed">
              Our company will implement necessary and appropriate measures for the safe management of user information, including education and training for all employees including our company officers, and system measures such as implementing access restrictions to user information files, recording access logs, and implementing security measures to prevent unauthorized access from outside to prevent leakage, loss, or damage of user information.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">8. Use of Cookies</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              Our company automatically collects user access data using cookies when using this Service to improve the convenience of this Service.
            </p>
            <p className="text-gray-300 leading-relaxed mb-4">
              Cookies are information such as website access history sent from the server and saved as small data files on the user's computer, and are a mechanism to identify users. Cookies do not contain information that identifies individual users such as names or addresses. You can delete cookies from the "Settings" of each browser. However, please note that deleting cookies may affect some functions.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">9. Scope of Privacy Policy</h2>
            <p className="text-gray-300 leading-relaxed">
              This Privacy Policy does not apply to our company's business partners, outsourcing companies, or linked sites within our company's website. Our company assumes no responsibility for any troubles that occur on those sites. Please check the handling of user information on each site.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">10. Revision of Privacy Policy</h2>
            <p className="text-gray-300 leading-relaxed">
              Our company will review the operation status of user information handling as appropriate and strive for continuous improvement, and may revise this Policy as necessary. We will notify users of revisions to the Privacy Policy by methods such as notifying users or posting on our company's website.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">11. Contact Window</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              For questions or complaints regarding the handling of user information by our company, please contact the following window.
            </p>
            <p className="text-gray-300">
              <strong>Contact:</strong> support@Cription.ai
            </p>
            <p className="text-gray-300 mt-4">
              Established: November 29, 2019<br />
              Revised: August 1, 2025<br />
              Cription Corporation
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}